# Generated by Django 4.0.3 on 2022-03-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='assets/carro.jpg', upload_to='static/assets', verbose_name='Foto'),
        ),
    ]
