# Generated by Django 4.0.3 on 2022-03-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_marca_photo_alter_car_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='desc',
            field=models.TextField(default='', verbose_name='Descrição'),
        ),
    ]
